site_name: ChainReactor Wiki
site_description: chainreactors wiki
site_author: M09ic
site_url: https://chainreactors.github.io/wiki/
repo_url: https://github.com/chainreactors/
copyright: Copyright &copy; 2022 ChainReactors

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chainreactors
  analytics:
    provider: google
    property: G-DCRVR86FG2
theme:
  features:
    - navigation.tracking
    - navigation.tabs 
    - navigation.tabs.sticky 
    - navigation.sections 
    - navigation.expand
    - navigation.indexes
    - toc.integrate 
    - toc.follow
    - navigation.top 
    - header.autohide
    - search.share
    - search.suggest 
    - search.highlight 

  name: material
plugins:
  - search
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 导航: index.md
  - gogo: 
    - index: gogo/index.md
    - 入门: gogo/start.md
    - 设计: gogo/design.md
    - 细节: gogo/detail.md 
    - 拓展: gogo/extension.md
    - 实战: gogo/do.md
  - spray:
    - index: spray/index.md
    - 入门: spray/start.md
    - 设计: spray/design.md
    - 细节: spray/detail.md
    - 实战: spray/do.md
  - zombie:
    - index: zombie/index.md
    - 入门: zombie/start.md
